language: java
cache:
  directories:
    - $HOME/.m2
jdk:
  - openjdk10
script:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  - provider: releases
    api_key: "$GITHUB_OATH_TOKEN"
    name: Build $(date '+%Y%m%d%H%M%S')-$TRAVIS_JOB_NUMBER
    file: "target/release.jar"
    skip_cleanup: true
    draft: true
    on:
      branch: master
      tags: true
notifications:
  email:
    on_failure: change
    on_success: never